# Generated by Django 4.2.13 on 2024-07-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
