# Generated by Django 4.2.13 on 2024-07-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='profesional',
            new_name='professional',
        ),
    ]
