# Generated by Django 4.2.13 on 2024-07-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_profesional_about_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(default='Your Name', max_length=100),
        ),
    ]
