# Generated by Django 4.2.13 on 2024-07-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Your Name', max_length=100),
        ),
    ]
