# Generated by Django 4.2.13 on 2024-07-09 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(validators=[django.core.validators.MaxLengthValidator(15), django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='treatment',
            field=models.IntegerField(choices=[(0, 'Botox Therapy(chronic pain relief)'), (1, 'Botox Treatment (wrinkle reduction/prevention)'), (2, 'Chemical Peel (skin rejuvenation)'), (3, 'Dermal Fillers (facce sculpting/wrinkle reduction)'), (4, 'Hyperhidrosis (excessive sweating treatment)'), (5, 'Lip filler (lip augmentation)'), (6, 'Skin: Hydrafacial'), (7, 'Skin: Profhilo Treatment'), (8, 'Wrinkle softening injections')]),
        ),
    ]
